spring:
  datasource:
    url: jdbc:mysql://localhost:3308/learning_camp?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:

  # 指定xml文件扫描路径
  mapper-locations: classpath:mapper/*Mapper.xml

  type-aliases-package: com.example.learning_camp.entity

